### PR TITLE
Start rebuilding project

### PR DESCRIPTION
**Pull request by 0x9n0p**
- Delete the entire old implementation.
- Add the new project structure.

### CODE REVIEW

**Comment by 0x9n0p** [comment]
@ddkwork

**Comment by ddkwork** [comment]
> @ddkwork

I'm sorry that at the moment I didn't choose fyne as the interface library because it is a tree and table widget that doesn't meet the requirements

**Comment by 0x9n0p** [comment]
The point of this PR is the structure of project.
Fyne can be changed.

**Comment by ddkwork** [comment]
> The point of this PR is the structure of project.
> Fyne can be changed.

You can totally implement one yourself, I don't see the value of merging on my side, so close the pr

**Pull request closed without merging**
